export const CALENDAR_MESSAGE_PATTERNS = {
  BULK_REGISTER_SHIFTS: 'calendar.bulk_register_shifts',
  GET_MY_SHIFTS: 'calendar.get_my_shifts',
  GET_ALL_SHIFTS: 'calendar.get_all_shifts',
  UPDATE_WORK_SHIFT: 'calendar.update_work_shift',
  DELETE_WORK_SHIFT: 'calendar.delete_work_shift',
  CREATE_LEAVE_REQUEST: 'calendar.create_leave_request',
  UPDATE_LEAVE_REQUEST: 'calendar.update_leave_request',
  DELETE_LEAVE_REQUEST: 'calendar.delete_leave_request',
  GET_LEAVE_REQUESTS: 'calendar.get_leave_requests',
  REVIEW_CALENDAR_REQUEST: 'calendar.review_calendar_request',
  APPROVE_LEAVE_REQUEST: 'calendar.approve_leave_request',
  REJECT_LEAVE_REQUEST: 'calendar.reject_leave_request',
  CHECK_IN: 'calendar.check_in',
  CHECK_OUT: 'calendar.check_out',
  GET_TODAY_ATTENDANCE: 'calendar.get_today_attendance',
  GET_PERSONAL_STATISTIC_SUMMARY: 'calendar.get_personal_statistic_summary',
  GET_PERSONAL_CHART_DATA: 'calendar.get_personal_chart_data',
  GET_WORKSPACE_STATISTIC_MEMBERS: 'calendar.get_workspace_statistic_members',
  EXPORT_WORKSPACE_STATISTIC_EXCEL: 'calendar.export_workspace_statistic_excel',
  UNLOCK_USER_CALENDAR: 'calendar.unlock_user_calendar',
  GET_CALENDAR_POLICY: 'calendar.get_policy',
  CREATE_CALENDAR_POLICY: 'calendar.create_policy',
  UPDATE_CALENDAR_POLICY: 'calendar.update_policy',
  DELETE_CALENDAR_POLICY: 'calendar.delete_policy',
  GET_MY_LEAVE_BALANCE: 'calendar.get_my_leave_balance',
  GET_WORKSPACE_LEAVE_BALANCES: 'calendar.get_workspace_leave_balances',
} as const;
