export const ORCHESTRATION_MESSAGE_PATTERNS = {
  GET_PROVIDERS: 'orchestration.get_providers',
  INITIATE_CONNECT: 'orchestration.initiate_connect',
  SUBMIT_CREDENTIALS: 'orchestration.submit_credentials',
  DISCONNECT_PROVIDER: 'orchestration.disconnect_provider',
  RESOLVE_APPROVAL: 'orchestration.resolve_approval',
  CANCEL_TURN: 'orchestration.cancel_turn',
  TRIGGER_PROMPT: 'orchestration.trigger_prompt',
  REGISTER_DYNAMIC_PROVIDER: 'orchestration.register_dynamic_provider',
  UPDATE_DYNAMIC_PROVIDER: 'orchestration.update_dynamic_provider',
  DELETE_DYNAMIC_PROVIDER: 'orchestration.delete_dynamic_provider',
  HEALTH_CHECK: 'orchestration.health_check',
  GET_METRICS: 'orchestration.get_metrics',
  EDGE_RELAY_LOGIN: 'orchestration.edge_relay_login',
} as const;
