export const TASK_MSG_PATTERN = {
  BOARD: {
    CREATE: 'board.create_new_board',
    UPDATE: 'board.update_board_info',
    DELETE: 'board.delete_board',
    GET_ALL_IN_WORKSPACE: 'board.get_boards_in_workspace',
    GET_DETAILS: 'board.get_board_details',
    GET_MEMBERS: 'board.get_board_members',
    ADD_MEMBER: 'board.add_member_to_board',
    REMOVE_MEMBER: 'board.remove_member_from_board',
  },
  GROUP: {
    CREATE: 'group.add_group_to_board',
    UPDATE: 'group.update_group_info',
    DELETE: 'group.remove_group_from_board',
    GET_ALL_IN_BOARD: 'group.get_groups_by_board_id',
  },
  TASK: {
    CREATE: 'task.create_new_task',
    UPDATE: 'task.update_task_details',
    DELETE: 'task.remove_task',
    GET_DETAILS: 'task.get_task_details',
    GET_ALL_IN_GROUP: 'task.get_tasks_in_group',
    GET_MEMBERS: 'task.get_task_members',
    ASSIGN_MEMBER: 'task.assign_member_to_task',
    UNASSIGN_MEMBER: 'task.unassign_member_from_task',
    TOGGLE_LABEL: 'task.toggle_task_label',
  },
  LABEL: {
    CREATE: 'label.create_new_label',
    UPDATE: 'label.update_label_info',
    DELETE: 'label.delete_label',
    GET_ALL_IN_WORKSPACE: 'label.get_labels_in_workspace',
  },
  CHECKLIST: {
    CREATE: 'checklist.create',
    UPDATE: 'checklist.update',
    DELETE: 'checklist.delete',
    GET_ALL_IN_TASK: 'checklist.get_all_in_task',
    ADD_ITEM: 'checklist.add_item',
    UPDATE_ITEM: 'checklist.update_item',
    DELETE_ITEM: 'checklist.delete_item',
    TOGGLE_ITEM: 'checklist.toggle_item',
  },
};
