export const WORKSPACE_MESSAGE_PATTERNS = {
  CREATE_WORKSPACE: 'workspace.create',
  UPDATE_WORKSPACE: 'workspace.update',
  DELETE_WORKSPACE: 'workspace.delete',
  INVITE_MEMBER: 'workspace.invite_member',
  REMOVE_MEMBER: 'workspace.remove_member',
  ADD_MEMBER_DIRECT: 'workspace.add_member_direct',
  ACCEPT_INVITE: 'workspace.accept_invite',
  LEAVE: 'workspace.leave',
  CHANGE_ROLE: 'workspace.change_role',
  TRANSFER_OWNERSHIP: 'workspace.transfer_ownership',
  RESEND_INVITE: 'workspace.resend_invite',
  REVOKE_INVITE: 'workspace.revoke_invite',
  GET_WORKSPACE: 'workspace.get',
  GET_WORKSPACES: 'workspace.get_all',
  GET_MEMBERS: 'workspace.get_members',
  GET_INVITES: 'workspace.get_invites',
  GET_LINKS: 'workspace.get_links',
  CREATE_LINK: 'workspace.create_link',
  DELETE_LINK: 'workspace.delete_link',
  DISABLE_LINK: 'workspace.disable_link',
} as const;
