export const BILLING_ERROR = {
  PLAN_NOT_FOUND: {
    code: 'ERR.BILLING.0101',
    message: 'PLAN NOT FOUND',
  },
  SUBSCRIPTION_NOT_FOUND: {
    code: 'ERR.BILLING.0102',
    message: 'SUBSCRIPTION NOT FOUND',
  },
  ALREADY_SUBSCRIBED: {
    code: 'ERR.BILLING.0103',
    message: 'USER IS ALREADY SUBSCRIBED TO THIS PLAN',
  },
  CHECKOUT_FAILED: {
    code: 'ERR.BILLING.0104',
    message: 'FAILED TO CREATE CHECKOUT SESSION',
  },
  PORTAL_FAILED: {
    code: 'ERR.BILLING.0105',
    message: 'FAILED TO CREATE CUSTOMER PORTAL SESSION',
  },
  INVALID_WEBHOOK_SIGNATURE: {
    code: 'ERR.BILLING.0106',
    message: 'INVALID STRIPE WEBHOOK SIGNATURE',
  },
  FEATURE_RESTRICTED: {
    code: 'ERR.BILLING.0107',
    message: 'THIS FEATURE REQUIRES A PAID SUBSCRIPTION',
  },
  STRIPE_CUSTOMER_NOT_FOUND: {
    code: 'ERR.BILLING.0108',
    message: 'STRIPE CUSTOMER NOT FOUND FOR THIS USER',
  },
};
