export const CALENDAR_ERROR = {
  CALENDAR_POLICY_NOT_FOUND: {
    code: 'ERR.CALENDAR.0101',
    message: 'WORKSPACE CALENDAR POLICY NOT FOUND',
  },
  CALENDAR_LOCKED: {
    code: 'ERR.CALENDAR.0102',
    message: 'CALENDAR IS LOCKED FOR THIS PERIOD',
  },
  WFH_LIMIT_EXCEEDED: {
    code: 'ERR.CALENDAR.0103',
    message: 'WFH DAYS LIMIT EXCEEDED FOR THIS MONTH',
  },
  MIN_HOURS_NOT_MET: {
    code: 'ERR.CALENDAR.0104',
    message: 'MINIMUM REQUIRED HOURS NOT MET',
  },
  MAX_HOURS_EXCEEDED: {
    code: 'ERR.CALENDAR.0105',
    message: 'MAXIMUM ALLOWED HOURS EXCEEDED',
  },
  LEAVE_REQUEST_NOT_FOUND: {
    code: 'ERR.CALENDAR.0106',
    message: 'LEAVE REQUEST NOT FOUND',
  },
  INVALID_IP_ADDRESS: {
    code: 'ERR.CALENDAR.0107',
    message: 'INVALID IP ADDRESS FOR OFFICE TIMEKEEPING',
  },
  FACE_NOT_MATCH: {
    code: 'ERR.CALENDAR.0108',
    message: 'FACE AUTHENTICATION DID NOT MATCH BASELINE IMAGE',
  },
  SHIFT_NOT_FOUND: {
    code: 'ERR.CALENDAR.0109',
    message: 'WORK SHIFT NOT FOUND',
  },
  ALREADY_CHECKED_IN: {
    code: 'ERR.CALENDAR.0110',
    message: 'ALREADY CHECKED IN FOR THIS SHIFT',
  },
  ALREADY_CHECKED_OUT: {
    code: 'ERR.CALENDAR.0111',
    message: 'ALREADY CHECKED OUT FOR THIS SHIFT',
  },
  NO_ACTIVE_SHIFT: {
    code: 'ERR.CALENDAR.0112',
    message: 'NO ACTIVE SHIFT FOUND FOR TIMEKEEPING TODAY',
  },
  CALENDAR_LOCK_RECORD_NOT_FOUND: {
    code: 'ERR.CALENDAR.0113',
    message: 'CALENDAR LOCK RECORD NOT FOUND',
  },
  NOT_WORKSPACE_MEMBER: {
    code: 'ERR.CALENDAR.0114',
    message: 'USER IS NOT A MEMBER OF THIS WORKSPACE',
  },
  INVALID_TIME_UTC: {
    code: 'ERR.CALENDAR.0115',
    message: 'TIME MUST BE A STRICTLY UTC ISO STRING ENDING WITH Z',
  },
  BULK_REGISTER_FAILED: {
    code: 'ERR.CALENDAR.0116',
    message: 'FAILED TO BULK REGISTER SHIFTS',
  },
  FETCH_SHIFTS_FAILED: {
    code: 'ERR.CALENDAR.0117',
    message: 'FAILED TO FETCH WORK SHIFTS',
  },
  UPDATE_SHIFT_FAILED: {
    code: 'ERR.CALENDAR.0118',
    message: 'FAILED TO UPDATE WORK SHIFT',
  },
  DELETE_SHIFT_FAILED: {
    code: 'ERR.CALENDAR.0119',
    message: 'FAILED TO DELETE WORK SHIFT',
  },
  POLICY_MANAGEMENT_FORBIDDEN: {
    code: 'ERR.CALENDAR.0120',
    message: 'YOU DO NOT HAVE PERMISSION TO MANAGE POLICY',
  },
  POLICY_ALREADY_EXISTS: {
    code: 'ERR.CALENDAR.0121',
    message: 'WORKSPACE ALREADY HAS A POLICY',
  },
  CREATE_POLICY_FAILED: {
    code: 'ERR.CALENDAR.0122',
    message: 'FAILED TO CREATE CALENDAR POLICY',
  },
  UPDATE_POLICY_FAILED: {
    code: 'ERR.CALENDAR.0123',
    message: 'FAILED TO UPDATE CALENDAR POLICY',
  },
  DELETE_POLICY_FAILED: {
    code: 'ERR.CALENDAR.0124',
    message: 'FAILED TO DELETE CALENDAR POLICY',
  },
};
