export const CALENDAR_ERROR = {
  CALENDAR_POLICY_NOT_FOUND: {
    code: 'ERR.CALENDAR.0101',
    message: 'WORKSPACE CALENDAR POLICY NOT FOUND',
  },
  CALENDAR_LOCKED: {
    code: 'ERR.CALENDAR.0102',
    message: 'CALENDAR IS LOCKED FOR THIS PERIOD',
  },
  WFH_LIMIT_EXCEEDED: {
    code: 'ERR.CALENDAR.0103',
    message: 'WFH DAYS LIMIT EXCEEDED FOR THIS MONTH',
  },
  MIN_HOURS_NOT_MET: {
    code: 'ERR.CALENDAR.0104',
    message: 'MINIMUM REQUIRED HOURS NOT MET',
  },
  MAX_HOURS_EXCEEDED: {
    code: 'ERR.CALENDAR.0105',
    message: 'MAXIMUM ALLOWED HOURS EXCEEDED',
  },
  LEAVE_REQUEST_NOT_FOUND: {
    code: 'ERR.CALENDAR.0106',
    message: 'LEAVE REQUEST NOT FOUND',
  },
  INVALID_IP_ADDRESS: {
    code: 'ERR.CALENDAR.0107',
    message: 'INVALID IP ADDRESS FOR OFFICE TIMEKEEPING',
  },
  FACE_NOT_MATCH: {
    code: 'ERR.CALENDAR.0108',
    message: 'FACE AUTHENTICATION DID NOT MATCH BASELINE IMAGE',
  },
  SHIFT_NOT_FOUND: {
    code: 'ERR.CALENDAR.0109',
    message: 'WORK SHIFT NOT FOUND',
  },
  ALREADY_CHECKED_IN: {
    code: 'ERR.CALENDAR.0110',
    message: 'ALREADY CHECKED IN FOR THIS SHIFT',
  },
  ALREADY_CHECKED_OUT: {
    code: 'ERR.CALENDAR.0111',
    message: 'ALREADY CHECKED OUT FOR THIS SHIFT',
  },
  NO_ACTIVE_SHIFT: {
    code: 'ERR.CALENDAR.0112',
    message: 'NO ACTIVE SHIFT FOUND FOR TIMEKEEPING TODAY',
  },
  CALENDAR_LOCK_RECORD_NOT_FOUND: {
    code: 'ERR.CALENDAR.0113',
    message: 'CALENDAR LOCK RECORD NOT FOUND',
  },
};
