export const CALENDAR_ERROR = {
  CALENDAR_POLICY_NOT_FOUND: {
    code: 'ERR.CALENDAR.0101',
    message: 'WORKSPACE CALENDAR POLICY NOT FOUND',
  },
  CALENDAR_LOCKED: {
    code: 'ERR.CALENDAR.0102',
    message: 'CALENDAR IS LOCKED FOR THIS PERIOD',
  },
  SHIFT_OVERLAP: {
    code: 'ERR.CALENDAR.0113',
    message: 'SHIFT TIMES OVERLAP',
  },
  WFH_LIMIT_EXCEEDED: {
    code: 'ERR.CALENDAR.0103',
    message: 'WFH DAYS LIMIT EXCEEDED FOR THIS MONTH',
  },
  MIN_HOURS_NOT_MET: {
    code: 'ERR.CALENDAR.0104',
    message: 'MINIMUM REQUIRED HOURS NOT MET',
  },
  MAX_HOURS_EXCEEDED: {
    code: 'ERR.CALENDAR.0105',
    message: 'MAXIMUM ALLOWED HOURS EXCEEDED',
  },
  LEAVE_REQUEST_NOT_FOUND: {
    code: 'ERR.CALENDAR.0106',
    message: 'LEAVE REQUEST NOT FOUND',
  },
  INVALID_IP_ADDRESS: {
    code: 'ERR.CALENDAR.0107',
    message: 'INVALID IP ADDRESS FOR OFFICE TIMEKEEPING',
  },
  FACE_NOT_MATCH: {
    code: 'ERR.CALENDAR.0108',
    message: 'FACE AUTHENTICATION DID NOT MATCH BASELINE IMAGE',
  },
  SHIFT_NOT_FOUND: {
    code: 'ERR.CALENDAR.0109',
    message: 'WORK SHIFT NOT FOUND',
  },
  ALREADY_CHECKED_IN: {
    code: 'ERR.CALENDAR.0110',
    message: 'ALREADY CHECKED IN FOR THIS SHIFT',
  },
  ALREADY_CHECKED_OUT: {
    code: 'ERR.CALENDAR.0111',
    message: 'ALREADY CHECKED OUT FOR THIS SHIFT',
  },
  NO_ACTIVE_SHIFT: {
    code: 'ERR.CALENDAR.0112',
    message: 'NO ACTIVE SHIFT FOUND FOR TIMEKEEPING TODAY',
  },
  CALENDAR_LOCK_RECORD_NOT_FOUND: {
    code: 'ERR.CALENDAR.0113',
    message: 'CALENDAR LOCK RECORD NOT FOUND',
  },
  NOT_WORKSPACE_MEMBER: {
    code: 'ERR.CALENDAR.0114',
    message: 'USER IS NOT A MEMBER OF THIS WORKSPACE',
  },
  INVALID_TIME_UTC: {
    code: 'ERR.CALENDAR.0115',
    message: 'TIME MUST BE A STRICTLY UTC ISO STRING ENDING WITH Z',
  },
  BULK_REGISTER_FAILED: {
    code: 'ERR.CALENDAR.0116',
    message: 'FAILED TO BULK REGISTER SHIFTS',
  },
  FETCH_SHIFTS_FAILED: {
    code: 'ERR.CALENDAR.0117',
    message: 'FAILED TO FETCH WORK SHIFTS',
  },
  UPDATE_SHIFT_FAILED: {
    code: 'ERR.CALENDAR.0118',
    message: 'FAILED TO UPDATE WORK SHIFT',
  },
  DELETE_SHIFT_FAILED: {
    code: 'ERR.CALENDAR.0119',
    message: 'FAILED TO DELETE WORK SHIFT',
  },
  POLICY_MANAGEMENT_FORBIDDEN: {
    code: 'ERR.CALENDAR.0120',
    message: 'YOU DO NOT HAVE PERMISSION TO MANAGE POLICY',
  },
  POLICY_ALREADY_EXISTS: {
    code: 'ERR.CALENDAR.0121',
    message: 'WORKSPACE ALREADY HAS A POLICY',
  },
  CREATE_POLICY_FAILED: {
    code: 'ERR.CALENDAR.0122',
    message: 'FAILED TO CREATE CALENDAR POLICY',
  },
  UPDATE_POLICY_FAILED: {
    code: 'ERR.CALENDAR.0123',
    message: 'FAILED TO UPDATE CALENDAR POLICY',
  },
  DELETE_POLICY_FAILED: {
    code: 'ERR.CALENDAR.0124',
    message: 'FAILED TO DELETE CALENDAR POLICY',
  },
  INSUFFICIENT_LEAVE_BALANCE: {
    code: 'ERR.CALENDAR.0125',
    message: 'INSUFFICIENT LEAVE BALANCE',
  },
  CREATE_REQUEST_FAILED: {
    code: 'ERR.CALENDAR.0126',
    message: 'FAILED TO CREATE CALENDAR REQUEST',
  },
  UPDATE_REQUEST_FAILED: {
    code: 'ERR.CALENDAR.0127',
    message: 'FAILED TO UPDATE CALENDAR REQUEST',
  },
  DELETE_REQUEST_FAILED: {
    code: 'ERR.CALENDAR.0128',
    message: 'FAILED TO DELETE CALENDAR REQUEST',
  },
  REQUEST_NOT_PENDING: {
    code: 'ERR.CALENDAR.0129',
    message: 'ONLY PENDING REQUESTS CAN BE MODIFIED OR DELETED',
  },
  REQUEST_FORBIDDEN_ACTION: {
    code: 'ERR.CALENDAR.0130',
    message: 'YOU DO NOT HAVE PERMISSION TO MODIFY THIS REQUEST',
  },
  REQUEST_ALREADY_PROCESSED: {
    code: 'ERR.CALENDAR.0131',
    message: 'THIS REQUEST HAS ALREADY BEEN PROCESSED',
  },
  REVIEW_REQUEST_FORBIDDEN: {
    code: 'ERR.CALENDAR.0132',
    message: 'ONLY MANAGERS OR ADMINS CAN REVIEW REQUESTS',
  },
  REVIEW_REQUEST_FAILED: {
    code: 'ERR.CALENDAR.0133',
    message: 'FAILED TO REVIEW CALENDAR REQUEST',
  },
  MANUAL_UNLOCK_FORBIDDEN: {
    code: 'ERR.CALENDAR.0134',
    message: 'ONLY MANAGERS OR ADMINS CAN MANUALLY UNLOCK CALENDARS',
  },
  MANUAL_UNLOCK_FAILED: {
    code: 'ERR.CALENDAR.0135',
    message: 'FAILED TO MANUALLY UNLOCK CALENDAR',
  },
  SHIFT_ACCESS_FORBIDDEN: {
    code: 'ERR.CALENDAR.0136',
    message: 'YOU DO NOT HAVE PERMISSION TO ACCESS OR MODIFY THIS SHIFT',
  },
  FETCH_LEAVE_BALANCE_FAILED: {
    code: 'ERR.CALENDAR.0137',
    message: 'FAILED TO FETCH LEAVE BALANCE',
  },
  FETCH_LEAVE_BALANCES_FAILED: {
    code: 'ERR.CALENDAR.0138',
    message: 'FAILED TO FETCH WORKSPACE LEAVE BALANCES',
  },
  OVERLAPPING_REQUEST: {
    code: 'ERR.CALENDAR.0139',
    message: 'YOU ALREADY HAVE AN OVERLAPPING REQUEST IN THIS TIME PERIOD',
  },
  INVALID_TIME_RANGE: {
    code: 'ERR.CALENDAR.0140',
    message: 'START TIME MUST BE BEFORE END TIME',
  },
  ONLY_OWNER_CAN_UPDATE_NOTES: {
    code: 'ERR.CALENDAR.0141',
    message: 'ONLY THE SHIFT OWNER CAN UPDATE NOTES',
  },
  REQUEST_ALREADY_PROCESSED_OR_STARTED: {
    code: 'ERR.CALENDAR.0142',
    message: 'THIS REQUEST HAS ALREADY BEEN PROCESSED OR HAS ALREADY STARTED',
  },
  IP_NOT_IN_OFFICE_NETWORK: {
    code: 'ERR.CALENDAR.0143',
    message: 'IP ADDRESS IS NOT IN THE OFFICE NETWORK. PLEASE CONNECT TO OFFICE WIFI.',
  },
  WFH_REQUIRES_FACE_AUTH: {
    code: 'ERR.CALENDAR.0144',
    message: 'WFH REQUIRES FACE AUTHENTICATION. PLEASE ENABLE YOUR CAMERA.',
  },
  ATTENDANCE_FAILED: {
    code: 'ERR.CALENDAR.0145',
    message: 'ATTENDANCE FAILED. PLEASE TRY AGAIN.',
  },
  START_TIME_FAR_FROM_WORK_DATE: {
    code: 'ERR.CALENDAR.0146',
    message: 'START TIME IS TOO FAR FROM WORK DATE',
  },
  NOT_IN_SHIFT_TIME: {
    code: 'ERR.CALENDAR.0147',
    message: 'YOU CANNOT CHECK IN OR CHECK OUT AT THIS TIME. PLEASE ENSURE IT IS WITHIN YOUR SHIFT TIME.',
  },
  MISSING_CHECK_IN: {
    code: 'ERR.CALENDAR.0148',
    message: 'YOU MUST CHECK IN BEFORE YOU CAN CHECK OUT.',
  },
  SHIFT_REQUIRED_FOR_ATTENDANCE: {
    code: 'ERR.CALENDAR.0149',
    message: 'A WORK SHIFT IS REQUIRED FOR ATTENDANCE. FREE CHECK-IN IS NOT ALLOWED.',
  },
  HOLIDAY_NOT_FOUND: {
    code: 'ERR.CALENDAR.0150',
    message: 'HOLIDAY NOT FOUND',
  },
  HOLIDAY_ALREADY_EXISTS: {
    code: 'ERR.CALENDAR.0151',
    message: 'HOLIDAY ALREADY EXISTS ON THIS DATE',
  },
  UNSUPPORTED_COUNTRY_HOLIDAY_AUTO_FILL: {
    code: 'ERR.CALENDAR.0152',
    message: 'AUTO-FILL HOLIDAYS FOR THIS COUNTRY IS NOT SUPPORTED',
  },
};
