export const INTEGRATION_ERROR = {
  PROVIDER_NOT_SUPPORTED: {
    code: 'ERR.INTEGRATION.0400',
    message: 'INTEGRATION PROVIDER IS NOT SUPPORTED',
  },
  OAUTH_FAILED: {
    code: 'ERR.INTEGRATION.0401',
    message: 'FAILED TO AUTHENTICATE WITH EXTERNAL PROVIDER',
  },
  CONNECTION_NOT_FOUND: {
    code: 'ERR.INTEGRATION.0404',
    message: 'USER HAS NOT CONNECTED TO THIS INTEGRATION',
  },
  SYNC_FAILED: {
    code: 'ERR.INTEGRATION.0500',
    message: 'FAILED TO SYNC DATA WITH EXTERNAL PROVIDER',
  },
  INVALID_STATE: {
    code: 'ERR.INTEGRATION.0402',
    message: 'INVALID OR EXPIRED OAUTH STATE',
  },
};
