export const NOTIFICATION_ERROR = {
  SEND_VERIFICATION_EMAIL_FAILED: {
    code: 'ERR.NOTI.0101',
    message: 'FAILED TO SEND VERIFICATION EMAIL',
  },
  SEND_RESET_PASSWORD_EMAIL_FAILED: {
    code: 'ERR.NOTI.0102',
    message: 'FAILED TO SEND RESET PASSWORD EMAIL',
  },
};
