export const ORCHESTRATION_ERROR = {
  AGENT_NOT_REGISTERED: {
    code: 'ERR.ORCHESTRATION.0101',
    message: 'NO AGENT REGISTERED FOR THIS PROVIDER',
  },
  LLM_PROVIDER_NOT_CONFIGURED: {
    code: 'ERR.ORCHESTRATION.0102',
    message: 'API KEY FOR THIS LLM PROVIDER IS NOT CONFIGURED',
  },
  UNKNOWN_LLM_MODEL: {
    code: 'ERR.ORCHESTRATION.0105',
    message: 'REQUESTED MODEL IS NOT REGISTERED IN LLM_MODEL_REGISTRY',
  },
  PROVIDER_NOT_CONNECTED: {
    code: 'ERR.ORCHESTRATION.0103',
    message: 'PROVIDER IS NOT CONNECTED FOR THIS USER',
  },
  MCP_AUTH_REQUEST_FAILED: {
    code: 'ERR.ORCHESTRATION.0104',
    message: 'REQUEST TO MCP-AUTH FAILED',
  },
  CHECKPOINT_NOT_FOUND: {
    code: 'ERR.ORCHESTRATION.0106',
    message: 'NO PENDING APPROVAL CHECKPOINT FOR THIS MESSAGE',
  },
  CHECKPOINT_FORBIDDEN: {
    code: 'ERR.ORCHESTRATION.0107',
    message: 'ONLY THE USER WHO TRIGGERED THIS TURN CAN APPROVE OR REJECT IT',
  },
  CHECKPOINT_ALREADY_RESOLVED: {
    code: 'ERR.ORCHESTRATION.0108',
    message:
      'THIS CHECKPOINT WAS ALREADY APPROVED OR REJECTED BY ANOTHER REQUEST',
  },
  CIRCUIT_BREAKER_OPEN: {
    code: 'ERR.ORCHESTRATION.0109',
    message: 'THIS PROVIDER IS TEMPORARILY UNAVAILABLE (CIRCUIT BREAKER OPEN)',
  },
  INVALID_OPENAPI_SPEC: {
    code: 'ERR.ORCHESTRATION.0110',
    message: 'FAILED TO PARSE OPENAPI SPECIFICATION',
  },
  DYNAMIC_PROVIDER_NOT_FOUND: {
    code: 'ERR.ORCHESTRATION.0111',
    message: 'DYNAMIC PROVIDER NOT FOUND IN DATABASE',
  },
  DATABASE_OPERATION_FAILED: {
    code: 'ERR.ORCHESTRATION.0112',
    message: 'DATABASE OPERATION FAILED',
  },
  OAUTH2_REFRESH_FAILED: {
    code: 'ERR.ORCHESTRATION.0113',
    message:
      'FAILED TO OBTAIN AN ACCESS TOKEN WITH THE PROVIDED OAUTH2 REFRESH CREDENTIALS',
  },
  INVALID_AUTH_CONFIG: {
    code: 'ERR.ORCHESTRATION.0114',
    message:
      'AUTH TYPE REQUIRES CREDENTIALS BUT NONE ARE CONFIGURED (NO ACCESS TOKEN, NO REFRESH TOKEN + TOKEN URL)',
  },
  TURN_NOT_FOUND: {
    code: 'ERR.ORCHESTRATION.0115',
    message:
      'NO RUNNING TURN FOUND FOR THIS MESSAGE (ALREADY FINISHED OR NEVER STARTED)',
  },
  TURN_FORBIDDEN: {
    code: 'ERR.ORCHESTRATION.0116',
    message: 'ONLY THE USER WHO TRIGGERED THIS TURN CAN STOP IT',
  },
  // accuracy_problem.md mục 1 — action="clarify" chỉ hợp lệ cho checkpoint
  // kind='clarification' kèm selectedProvider; action="approve"/"reject" chỉ
  // hợp lệ cho kind='approval'.
  CHECKPOINT_ACTION_MISMATCH: {
    code: 'ERR.ORCHESTRATION.0117',
    message: 'THIS ACTION DOES NOT MATCH THE CHECKPOINT KIND',
  },
};
