export const ORCHESTRATION_ERROR = {
    AGENT_NOT_REGISTERED: {
        code: 'ERR.ORCHESTRATION.0101',
        message: 'NO AGENT REGISTERED FOR THIS PROVIDER',
    },
    LLM_PROVIDER_NOT_CONFIGURED: {
        code: 'ERR.ORCHESTRATION.0102',
        message: 'API KEY FOR THIS LLM PROVIDER IS NOT CONFIGURED',
    },
    UNKNOWN_LLM_MODEL: {
        code: 'ERR.ORCHESTRATION.0105',
        message: 'REQUESTED MODEL IS NOT REGISTERED IN LLM_MODEL_REGISTRY',
    },
    PROVIDER_NOT_CONNECTED: {
        code: 'ERR.ORCHESTRATION.0103',
        message: 'PROVIDER IS NOT CONNECTED FOR THIS USER',
    },
    MCP_AUTH_REQUEST_FAILED: {
        code: 'ERR.ORCHESTRATION.0104',
        message: 'REQUEST TO MCP-AUTH FAILED',
    },
    CHECKPOINT_NOT_FOUND: {
        code: 'ERR.ORCHESTRATION.0106',
        message: 'NO PENDING APPROVAL CHECKPOINT FOR THIS MESSAGE',
    },
    CHECKPOINT_FORBIDDEN: {
        code: 'ERR.ORCHESTRATION.0107',
        message: 'ONLY THE USER WHO TRIGGERED THIS TURN CAN APPROVE OR REJECT IT',
    },
    CHECKPOINT_ALREADY_RESOLVED: {
        code: 'ERR.ORCHESTRATION.0108',
        message: 'THIS CHECKPOINT WAS ALREADY APPROVED OR REJECTED BY ANOTHER REQUEST',
    },
};
