export const PORT_TCP = {
  AUTH_TCP_PORT: 3001,
  USER_TCP_PORT: 3002,
  WORKSPACE_TCP_PORT: 3003,
  CHANNEL_TCP_PORT: 3004,
  MESSAGE_TCP_PORT: 3005,
  NOTIFICATION_TCP_PORT: 3007,
};

export const NAME_SERVICE_TCP = {
  AUTH_SERVICE: 'AUTH_SERVICE',
  USER_SERVICE: 'USER_SERVICE',
  WORKSPACE_SERVICE: 'WORKSPACE_SERVICE',
  CHANNEL_SERVICE: 'CHANNEL_SERVICE',
  MESSAGE_SERVICE: 'MESSAGE_SERVICE',
  NOTIFICATION_SERVICE: 'NOTIFICATION_SERVICE',
};
