export enum AuditAction {
  // channel
  CHANNEL_CREATED = 'CHANNEL_CREATED',
  CHANNEL_RENAMED = 'CHANNEL_RENAMED',
  CHANNEL_DELETED = 'CHANNEL_DELETED',
  USER_ADDED_TO_CHANNEL = 'USER_ADDED_TO_CHANNEL',

  USER_REMOVED_FROM_CHANNEL = 'USER_REMOVED_FROM_CHANNEL',

  // workspace
  WORKSPACE_CREATED = 'WORKSPACE_CREATED',
  WORKSPACE_RENAMED = 'WORKSPACE_RENAMED',
  WORKSPACE_DELETED = 'WORKSPACE_DELETED',
  USER_INVITED_TO_WORKSPACE = 'USER_INVITED_TO_WORKSPACE',

  USER_JOINED_WORKSPACE = 'USER_JOINED_WORKSPACE',


  // message
  MESSAGE_EDITED = 'MESSAGE_EDITED',
  MESSAGE_DELETED = 'MESSAGE_DELETED',

  // task
  TASK_CREATED = 'TASK_CREATED',
  TASK_ASSIGNED = 'TASK_ASSIGNED',
  TASK_UPDATED = 'TASK_UPDATED',
  TASK_DELETED = 'TASK_DELETED',

}

export enum AuditEntityType {
  CHANNEL = 'CHANNEL',
  WORKSPACE = 'WORKSPACE',
  MESSAGE = 'MESSAGE',
  TASK = 'TASK',
}
