import { MigrationInterface, QueryRunner } from 'typeorm';

export class RemoveShiftUniqueConstraint1782040000000 implements MigrationInterface {
  name = 'RemoveShiftUniqueConstraint1782040000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    // Drop the unique constraint that was generated by the @Unique decorator
    await queryRunner.query(`ALTER TABLE "work_shifts" DROP CONSTRAINT IF EXISTS "IDX_UNIQUE_SHIFT_PER_DAY"`);
    // Just in case it was created as a regular unique index in some environments
    await queryRunner.query(`DROP INDEX IF EXISTS "IDX_UNIQUE_SHIFT_PER_DAY"`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // Re-add the unique constraint
    await queryRunner.query(
      `ALTER TABLE "work_shifts" ADD CONSTRAINT "IDX_UNIQUE_SHIFT_PER_DAY" UNIQUE ("userId", "workspaceId", "workDate")`,
    );
  }
}
