[databases]
# Cú pháp: tên_db_ảo = host=địa_chỉ_pg port=cổng_pg dbname=tên_db_thật
# Khi chạy bằng Docker, host là tên service postgres (ví dụ: postgres_db hoặc 127.0.0.1)
slack_db = host=host.docker.internal port=5434 dbname=slack_db

[pgbouncer]
# logfile = /var/log/pgbouncer/pgbouncer.log
# pidfile = /var/run/pgbouncer/pgbouncer.pid

# Chế độ hoạt động quan trọng nhất cho NestJS/Microservices (Transaction Pooling)
pool_mode = transaction

# Cấu hình kết nối lắng nghe
listen_addr = 0.0.0.0
listen_port = 6432

# Cơ chế xác thực
auth_type = md5
auth_file = /etc/pgbouncer/userlist.txt

# Giới hạn kết nối (Tối ưu cho High Concurrency)
# Tối đa 5,000 kết nối ảo từ các NestJS services
max_client_conn = 5000
# Duy trì 50 kết nối vật lý tới PostgreSQL
default_pool_size = 50
# Tối thiểu 10 kết nối vật lý luôn mở
min_pool_size = 10
# Mở thêm 10 kết nối dự phòng khi tải tăng đột biến
reserve_pool_size = 10
# Thời gian chờ trước khi dùng kết nối dự phòng
reserve_pool_timeout = 5

# Tối ưu hóa & Ổn định
# Không bao giờ vượt quá 100 kết nối vật lý tới DB
max_db_connections = 100
server_reset_query = DISCARD ALL
server_check_query = select 1
server_check_delay = 30

# Bỏ qua các tham số khởi tạo không được hỗ trợ từ phía Driver Postgres
ignore_startup_parameters = extra_float_digits, uppercase_attribute_names
